[client.pv.activation]
proximity = "Blízkost"

[server.pv.command.list]
empty = "nejsou nainstalováni žádní hráči s Plasmo Voice"
message = "Klienti (%1$s/%2$s): %3$s"

[server.pv.command.mute]
already_muted = "%s je již ztlumený"
permanently_muted = "%1$s je natrvalo ztlumen. Důvod: %2$s"
temporarily_muted = "Ztlumen %1$s %2$s. Důvod: %3$s"
usage = "Využití: /vmute <player> [trvání] [důvod]"

[server.pv.command.mute_list]
empty = "Žádní hráči nejsou ztlumeni"
entry = "%1$s, vyprší: %2$s. Důvod: %3$s"
entry_muted_by = "%1$s umlčel %2$s, vyprší: %3$s. Důvod: %4$s"
expiration_date = "dd.MM.rrrr"
expiration_time = "HH:mm:ss"
expire_at = "%1$s v %2$s"
header = "Ztlumení hráči:"
never_expires = "nikdy"

[server.pv.command.reconnect]
message = "Znovupřipojení na paket byl odeslán"

[server.pv.command.reload]
message = "Konfigurace obnovena"

[server.pv.command.unmute]
not_muted = "%s není ztlumen"
unmuted = "Zrušeno ztlumení %s"
usage = "Využití: /vuntumlit <player>"

[server.pv.error]
mod_missing_kick_message = """
Omlouváme se, na tomto serveru musíte mít Plasmo Voice mód, aby jste mohli hrát.
Stáhněte si zde: https://modrinth.com/plugin/plasmo-voice"""
no_permissions = "&cOmlouvám se, ale nemáte oprávnění k provedení tohoto příkazu. Pokud se domníváte, že se jedná o omyl, kontaktujte správce serveru."
player_not_found = "Hráč nenalezen"
player_only_command = "Pouze hráč mohou provést tento příkaz"
version_not_supported = "Omlouváme se, ale vaše verze Voice Plasmo není na tomto serveru podporována. %s"
version_not_supported_click = "Stáhněte si podporovanou verzi"
version_not_supported_hover = "%s"

[server.pv.mutes]
empty_reason = "nespecifikováno"
permanently_muted = "Byl jsi natrvalo ztlumen. Důvod: %s"
temporarily_muted = "Byl jsi ztlumen %1$s. Důvod: %2$s"
unmuted = "Byl jsi odtlumený"

[server.pv.mutes.durations]
days = "za %s d"
hours = "za %s h"
minutes = "za %s min"
seconds = "za %s s"
weeks = "za %s t"
