#Dimension-specific world border settings
[dimensions]

	[dimensions."minecraft:overworld"]
		size = 5.9999968E7
		center_x = 0.0
		center_z = 0.0
		damage_per_block = 0.2
		safe_zone = 5.0
		warning_blocks = 5
		warning_time = 15
		size_lerp_time = 0
		size_lerp_target = 5.9999968E7
