#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 14 11:15:18 EEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=MakeUp-UltraFast-9.5c.zip
