#Common
#Whether the dedicated server level-type default should be set to poopsky
setPoopskyDefault = true
#Whether the custom void generator should also keep the nether empty
voidNetherGeneration = true
#Whether to Enable the Desperate World (Enabling it will cause the device to lag)
desperateWorld = false
#Whether to Disable the consumption of liquid when sticks crafting
compooperCrafting = false
#Whether to Disable the underground lava lake
lavaFluid = true
#Whether to Disable the plug trades
plugTrades = false
#Whether to Disable the upgrade template trades
upgradeTemplate = false
#Whether to Enable the unlimited freeze
unlimitedFreeze = false
#Client
#Whether to Disable the freeze filter
freezeFilter = false
